In [1]:
import pandas as pd

In [5]:
obj = pd.Series([3,4,56,7], index = ['a','b','c','d'])

In [6]:
obj

a     3
b     4
c    56
d     7
dtype: int64

In [7]:
print(obj.values)
print(obj.index)

[ 3  4 56  7]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [8]:
sales = pd.Series([2,3,4,5], index = [3,4,5,6],name = 'Hourly Record')

In [9]:
sales

3    2
4    3
5    4
6    5
Name: Hourly Record, dtype: int64

In [10]:
sales.index

Int64Index([3, 4, 5, 6], dtype='int64')

In [11]:
sales.name

'Hourly Record'

In [12]:
sales.values

array([2, 3, 4, 5], dtype=int64)

In [13]:
sales.dtype

dtype('int64')

In [15]:
canteen_data = pd.Series([56,45,77,54,32,132,43], index = ['Monday','Tuesday','Wednesday','Thursday','Friday','saturday','Sunday'], name = 'sandwich Record')

In [16]:
canteen_data

Monday        56
Tuesday       45
Wednesday     77
Thursday      54
Friday        32
saturday     132
Sunday        43
Name: sandwich Record, dtype: int64

In [17]:
canteen_data[0]

56

In [18]:
canteen_data['Monday']

56

In [19]:
canteen_data[[3,5]]

Thursday     54
saturday    132
Name: sandwich Record, dtype: int64

In [20]:
canteen_data[['Thursday','saturday']]

Thursday     54
saturday    132
Name: sandwich Record, dtype: int64

In [21]:
canteen_data[canteen_data>100]

saturday    132
Name: sandwich Record, dtype: int64

In [22]:
city_canteen = canteen_data   * 2

In [23]:
city_canteen

Monday       112
Tuesday       90
Wednesday    154
Thursday     108
Friday        64
saturday     264
Sunday        86
Name: sandwich Record, dtype: int64

In [24]:
canteen_data

Monday        56
Tuesday       45
Wednesday     77
Thursday      54
Friday        32
saturday     132
Sunday        43
Name: sandwich Record, dtype: int64

In [25]:
city_canteen = city_canteen /2

In [26]:
city_canteen

Monday        56.0
Tuesday       45.0
Wednesday     77.0
Thursday      54.0
Friday        32.0
saturday     132.0
Sunday        43.0
Name: sandwich Record, dtype: float64

In [27]:
import numpy as np

In [34]:
arr = np.array([23,45,65,345,2312,4,32])

In [35]:
ind = np.array(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])

In [36]:
canteen_data = pd.Series(arr, index= ind ,name = 'Canteen Record')

In [37]:
canteen_data

Mon      23
Tue      45
Wed      65
Thu     345
Fri    2312
Sat       4
Sun      32
Name: Canteen Record, dtype: int32

In [38]:
canteen_data[canteen_data>100]

Thu     345
Fri    2312
Name: Canteen Record, dtype: int32

In [39]:
canteen_data[canteen_data<50]

Mon    23
Tue    45
Sat     4
Sun    32
Name: Canteen Record, dtype: int32

In [58]:
pay = {'a': 30000,'b': 3460,'c': 74572,'d': 7535} 

In [59]:
py = pd.Series(pay)

In [60]:
py

a    30000
b     3460
c    74572
d     7535
dtype: int64

In [61]:
py.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [62]:
py.values

array([30000,  3460, 74572,  7535], dtype=int64)

In [63]:
py>5000

a     True
b    False
c     True
d     True
dtype: bool

In [64]:
py[py>5000]

a    30000
c    74572
d     7535
dtype: int64

In [65]:
py['d']

7535

In [73]:
prr = np.array([232,531,5345,13])

In [74]:
py[3]

7535

In [75]:
py.ndim

1

In [76]:
py.dtype

dtype('int64')

In [77]:
py.shape

(4,)

In [78]:
py*3

a     90000
b     10380
c    223716
d     22605
dtype: int64

In [79]:
py 

a    30000
b     3460
c    74572
d     7535
dtype: int64

In [80]:
ty =pd.Series(prr, index = ['c','a','b','d'])

In [81]:
ty

c     232
a     531
b    5345
d      13
dtype: int32

In [84]:
a1 =np.array([23,512,23, 32])

In [93]:
indi = np.array(['d','b','c','a','e'])

In [94]:
d2 = {'a':442, 'b': 432, 'c':523, 'd':987}

In [95]:
arng = pd.Series(d2)

In [96]:
arng

a    442
b    432
c    523
d    987
dtype: int64

In [97]:
arng.values

array([442, 432, 523, 987], dtype=int64)

In [98]:
arng.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [99]:
arngn = pd.Series(d2 , index = indi)

In [100]:
arngn

d    987.0
b    432.0
c    523.0
a    442.0
e      NaN
dtype: float64

In [101]:
 t = pd.isnull(arngn)

In [102]:
t

d    False
b    False
c    False
a    False
e     True
dtype: bool

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
f1 = np.array([2,3,4,5])
f2 = np.array(['a','b','c','d'])

In [4]:
f3 = pd.Series(f1, index = f2)

In [5]:
f3

a    2
b    3
c    4
d    5
dtype: int32

In [6]:
f3.name = 'Pak'

In [7]:
f3.index.name = 'PAK'

In [8]:
f3

PAK
a    2
b    3
c    4
d    5
Name: Pak, dtype: int32

In [11]:
f1_f2 = {'k':8,'p':3,'q':7,'u':36,'t':54,}
f4 = pd.Series(f1_f2)

In [12]:
f4

k     8
p     3
q     7
u    36
t    54
dtype: int64

In [14]:
f1_f2_f3 = {'S1':f3,'S2':f4}

In [16]:
fff = pd.DataFrame(f1_f2_f3)

In [17]:
fff

S1    S2
a  2.0   NaN
b  3.0   NaN
c  4.0   NaN
d  5.0   NaN
k  NaN   8.0
p  NaN   3.0
q  NaN   7.0
t  NaN  54.0
u  NaN  36.0

In [18]:
phy = [23,345,34,34,233,234]

In [19]:
math = [213,2131,1231,12,213,12]

In [20]:
urdu = [2342,343,2,23,34,32]

In [21]:
sub = {'PHY': phy,
      'MATH':math,
      'URDU': urdu}

In [22]:
result = pd.DataFrame(sub)

In [23]:
result

PHY  MATH  URDU
0   23   213  2342
1  345  2131   343
2   34  1231     2
3   34    12    23
4  233   213    34
5  234    12    32

In [26]:
result.index = ['Ali','Usman','Kirn','Rani','Rashid','Noor']

In [27]:
result

PHY  MATH  URDU
Ali      23   213  2342
Usman   345  2131   343
Kirn     34  1231     2
Rani     34    12    23
Rashid  233   213    34
Noor    234    12    32

In [29]:
result[result<100]


PHY  MATH  URDU
Ali     23.0   NaN   NaN
Usman    NaN   NaN   NaN
Kirn    34.0   NaN   2.0
Rani    34.0  12.0  23.0
Rashid   NaN   NaN  34.0
Noor     NaN  12.0  32.0

In [30]:
re_arrange_subject_position = ['URDU','MATH','PHY']

In [31]:
result.columns = re_arrange_subject_position

In [32]:
result

URDU  MATH   PHY
Ali       23   213  2342
Usman    345  2131   343
Kirn      34  1231     2
Rani      34    12    23
Rashid   233   213    34
Noor     234    12    32

In [34]:
result = pd.DataFrame(sub,columns=['URDU','MATH','PHY'])

In [35]:
result

URDU  MATH  PHY
0  2342   213   23
1   343  2131  345
2     2  1231   34
3    23    12   34
4    34   213  233
5    32    12  234

In [36]:
columns1=['URDU','PHY','MATH']

In [37]:
result.columns= columns1

In [38]:
result

URDU   PHY  MATH
0  2342   213    23
1   343  2131   345
2     2  1231    34
3    23    12    34
4    34   213   233
5    32    12   234

In [40]:
result = pd.DataFrame(sub,columns=['URDU','PHY','MATH'])

In [41]:
result

URDU  PHY  MATH
0  2342   23   213
1   343  345  2131
2     2   34  1231
3    23   34    12
4    34  233   213
5    32  234    12

In [42]:
sub

{'PHY': [23, 345, 34, 34, 233, 234],
 'MATH': [213, 2131, 1231, 12, 213, 12],
 'URDU': [2342, 343, 2, 23, 34, 32]}

In [43]:
sub['PHY']

[23, 345, 34, 34, 233, 234]

In [44]:
result['PHY']

0     23
1    345
2     34
3     34
4    233
5    234
Name: PHY, dtype: int64

In [47]:
result.URDU

0    2342
1     343
2       2
3      23
4      34
5      32
Name: URDU, dtype: int64

In [63]:
result


URDU  MATH  PHY
Ali     2342   213   23
Usman    343  2131  345
Kirn       2  1231   34
Rani      23    12   34
Rashid    34   213  233
Noor      32    12  234

In [55]:
result = pd.DataFrame(sub,columns=['URDU','MATH','PHY'], index=['Ali','Usman','Kirn','Rani','Rashid','Noor'])

In [62]:
result


URDU  MATH  PHY
Ali     2342   213   23
Usman    343  2131  345
Kirn       2  1231   34
Rani      23    12   34
Rashid    34   213  233
Noor      32    12  234

In [60]:
result.loc['Ali']

URDU    2342
MATH     213
PHY       23
Name: Ali, dtype: int64

In [64]:
result = pd.DataFrame(sub,columns=['URDU','MATH','PHY'])

In [65]:
result.loc[0]

URDU    2342
MATH     213
PHY       23
Name: 0, dtype: int64

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [10]:
urdu = [21,234,342,321,13]
math = [24,23,32,21,134]
phy = [32,34,235,33,5]
stu = ['Ali','Usman','Fatima','Fizza','Noor']
sub = { 'URDU':[21,234,342,321,13],
       'MATH':[24,23,32,21,134],
       'PHY':[32,34,235,33,5]}

In [12]:
res = pd.DataFrame(sub, index= stu)

In [13]:
res

URDU  MATH  PHY
Ali       21    24   32
Usman    234    23   34
Fatima   342    32  235
Fizza    321    21   33
Noor      13   134    5

In [14]:
diffOf_min_max = lambda x : x.max()-x.min()

In [15]:
res.apply(diffOf_min_max)

URDU    329
MATH    113
PHY     230
dtype: int64

In [16]:
res.apply(diffOf_min_max, axis=1)

Ali        11
Usman     211
Fatima    310
Fizza     300
Noor      129
dtype: int64

In [22]:
def min_max(x):
    minimum = x.min()
    maximum = x.max()
    difference = maximum - minimum
    return pd.Series([maximum,minimum,difference], index=['max','min','diff'])

In [25]:
res.apply(min_max, axis= 1)

max  min  diff
Ali      32   21    11
Usman   234   23   211
Fatima  342   32   310
Fizza   321   21   300
Noor    134    5   129

In [26]:
res.apply(diffOf_min_max)

URDU    329
MATH    113
PHY     230
dtype: int64

In [45]:
New_Frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                         index= ['Ali','Hamza'],
                         columns=['d','a','b','c'])

In [46]:
New_Frame

d  a  b  c
Ali    0  1  2  3
Hamza  4  5  6  7

In [47]:
New_Frame.sort_index(axis = 1, ascending=True)

a  b  c  d
Ali    1  2  3  0
Hamza  5  6  7  4

In [48]:
New_Frame.sort_index(axis = 1, ascending=False)

d  c  b  a
Ali    0  3  2  1
Hamza  4  7  6  5

In [49]:
New_Frame.sort_index(axis = 1 , ascending=False)

d  c  b  a
Ali    0  3  2  1
Hamza  4  7  6  5

In [50]:
New_Frame.sort_index()

d  a  b  c
Ali    0  1  2  3
Hamza  4  5  6  7

In [53]:
New_Frame.sort_values(by="c")

d  a  b  c
Ali    0  1  2  3
Hamza  4  5  6  7

In [58]:
New_Frame.rank(ascending=True ,method='min')

d    a    b    c
Ali    1.0  1.0  1.0  1.0
Hamza  2.0  2.0  2.0  2.0

In [59]:
New_Frame.rank(ascending=True ,method='max')

d    a    b    c
Ali    1.0  1.0  1.0  1.0
Hamza  2.0  2.0  2.0  2.0

In [60]:
New_Frame.rank(ascending=False ,method='min')

d    a    b    c
Ali    2.0  2.0  2.0  2.0
Hamza  1.0  1.0  1.0  1.0

In [62]:
New_Frame.rank(ascending=False ,method='max')

d    a    b    c
Ali    2.0  2.0  2.0  2.0
Hamza  1.0  1.0  1.0  1.0

In [63]:
New_Frame.rank(axis='columns')

d    a    b    c
Ali    1.0  2.0  3.0  4.0
Hamza  1.0  2.0  3.0  4.0

In [64]:
New_Frame

d  a  b  c
Ali    0  1  2  3
Hamza  4  5  6  7

In [68]:
New_Frame.sum()

d     4
a     6
b     8
c    10
dtype: int64

In [69]:
New_Frame.sum(axis=0)

d     4
a     6
b     8
c    10
dtype: int64

In [70]:
New_Frame.sum(axis=1)

Ali       6
Hamza    22
dtype: int64

In [74]:
New_Frame.mean()

d    2.0
a    3.0
b    4.0
c    5.0
dtype: float64

In [75]:
New_Frame

d  a  b  c
Ali    0  1  2  3
Hamza  4  5  6  7

In [76]:
New_Frame.mean(axis=1)

Ali      1.5
Hamza    5.5
dtype: float64

In [77]:
New_Frame['a'].unique()

array([1, 5], dtype=int64)

In [80]:
data_df = pd.DataFrame(np.arange(16).reshape((4,4)),
                      index=['Lahore','Kasur','Okara','Sahiwal'],
                    columns= ['one','two','three','foure'])

In [81]:
data_df

one  two  three  foure
Lahore     0    1      2      3
Kasur      4    5      6      7
Okara      8    9     10     11
Sahiwal   12   13     14     15

In [90]:
data_df.loc['Kasur',['one','two']]

one    4
two    5
Name: Kasur, dtype: int32

In [91]:
data_df.loc[['Kasur','Lahore'],['one','two']]

one  two
Kasur     4    5
Lahore    0    1

In [92]:
data_df.iloc[[1,0],[0,1]]

one  two
Kasur     4    5
Lahore    0    1

In [93]:
data_df.iloc[:]

one  two  three  foure
Lahore     0    1      2      3
Kasur      4    5      6      7
Okara      8    9     10     11
Sahiwal   12   13     14     15

In [94]:
data_df.iloc[:, :3]

one  two  three
Lahore     0    1      2
Kasur      4    5      6
Okara      8    9     10
Sahiwal   12   13     14

In [95]:
data_df.iloc[:, :]

one  two  three  foure
Lahore     0    1      2      3
Kasur      4    5      6      7
Okara      8    9     10     11
Sahiwal   12   13     14     15

In [101]:
data_df.iloc[0:3:2, 0:3:2]

one  three
Lahore    0      2
Okara     8     10

In [104]:
data_df1= data_df.iloc[0:3]


In [105]:
data_df

one  two  three  foure
Lahore     0    1      2      3
Kasur      4    5      6      7
Okara      8    9     10     11
Sahiwal   12   13     14     15

In [106]:
data_df1

one  two  three  foure
Lahore    0    1      2      3
Kasur     4    5      6      7
Okara     8    9     10     11

In [107]:
data_df + data_df1

one   two  three  foure
Kasur     8.0  10.0   12.0   14.0
Lahore    0.0   2.0    4.0    6.0
Okara    16.0  18.0   20.0   22.0
Sahiwal   NaN   NaN    NaN    NaN

In [108]:
data_df2 = data_df1.add(data_df, fill_value=0)

In [109]:
data_df2

one   two  three  foure
Kasur     8.0  10.0   12.0   14.0
Lahore    0.0   2.0    4.0    6.0
Okara    16.0  18.0   20.0   22.0
Sahiwal  12.0  13.0   14.0   15.0

In [110]:
data_df2 = data_df.add(data_df1, fill_value=0)

In [111]:
data_df2

one   two  three  foure
Kasur     8.0  10.0   12.0   14.0
Lahore    0.0   2.0    4.0    6.0
Okara    16.0  18.0   20.0   22.0
Sahiwal  12.0  13.0   14.0   15.0

In [112]:
data_df + data_df1

one   two  three  foure
Kasur     8.0  10.0   12.0   14.0
Lahore    0.0   2.0    4.0    6.0
Okara    16.0  18.0   20.0   22.0
Sahiwal   NaN   NaN    NaN    NaN

In [113]:
 data_df1 + data_df  

one   two  three  foure
Kasur     8.0  10.0   12.0   14.0
Lahore    0.0   2.0    4.0    6.0
Okara    16.0  18.0   20.0   22.0
Sahiwal   NaN   NaN    NaN    NaN

In [114]:
data_df

one  two  three  foure
Lahore     0    1      2      3
Kasur      4    5      6      7
Okara      8    9     10     11
Sahiwal   12   13     14     15

In [118]:
s1 = pd.Series([2,3,4,5],index=list("abcd"))

In [119]:
s1

a    2
b    3
c    4
d    5
dtype: int64

In [120]:
data_df-s1

a   b   c   d  foure  one  three  two
Lahore  NaN NaN NaN NaN    NaN  NaN    NaN  NaN
Kasur   NaN NaN NaN NaN    NaN  NaN    NaN  NaN
Okara   NaN NaN NaN NaN    NaN  NaN    NaN  NaN
Sahiwal NaN NaN NaN NaN    NaN  NaN    NaN  NaN

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [39]:
math = [i for i in range(10,30,2)]
math

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [40]:
urdu = [i for i in range(30,50,2)]
urdu

[30, 32, 34, 36, 38, 40, 42, 44, 46, 48]

In [41]:
eng = [i for i in range(50,70,2)]
eng

[50, 52, 54, 56, 58, 60, 62, 64, 66, 68]

In [43]:
phy = [i for i in range(70,90,2)]
phy

[70, 72, 74, 76, 78, 80, 82, 84, 86, 88]

In [45]:
che = [i for i in range(90,100,1)]
che


[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [46]:
stu =['Imran','Irfan','Manfaz','Waqas','Jamil','Shahid','Asghar','Awais','Saqib','Aslam']

In [47]:
rec = {'MATH':math,
      'URDU':urdu,
      'ENG': eng,
      'PHY':phy,
      'CHEM':che}

In [48]:
result = pd.DataFrame(rec, index = stu)

In [53]:
result

MATH  URDU  ENG  PHY  CHEM
Imran     10    30   50   70    90
Irfan     12    32   52   72    91
Manfaz    14    34   54   74    92
Waqas     16    36   56   76    93
Jamil     18    38   58   78    94
Shahid    20    40   60   80    95
Asghar    22    42   62   82    96
Awais     24    44   64   84    97
Saqib     26    46   66   86    98
Aslam     28    48   68   88    99

In [59]:
result.loc[['Manfaz','Shahid'],['URDU','PHY']]

URDU  PHY
Manfaz    34   74
Shahid    40   80

In [70]:
result.iloc[[2,3,4,7],[2,3,4]]

ENG  PHY  CHEM
Manfaz   54   74    92
Waqas    56   76    93
Jamil    58   78    94
Awais    64   84    97

In [71]:
result.iloc[2:8,2:5]

ENG  PHY  CHEM
Manfaz   54   74    92
Waqas    56   76    93
Jamil    58   78    94
Shahid   60   80    95
Asghar   62   82    96
Awais    64   84    97

In [72]:
result.loc['Manfaz':'Awais','ENG':'CHEM']

ENG  PHY  CHEM
Manfaz   54   74    92
Waqas    56   76    93
Jamil    58   78    94
Shahid   60   80    95
Asghar   62   82    96
Awais    64   84    97

In [73]:
result.loc[:,'ENG':'CHEM']

ENG  PHY  CHEM
Imran    50   70    90
Irfan    52   72    91
Manfaz   54   74    92
Waqas    56   76    93
Jamil    58   78    94
Shahid   60   80    95
Asghar   62   82    96
Awais    64   84    97
Saqib    66   86    98
Aslam    68   88    99

In [74]:
new1 = np.arange(100).reshape((10,10))

In [77]:
new2 = np.arange(100,200).reshape((10,10))

In [78]:
D_new1 = pd.DataFrame(new1)

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [20]:
fram1 = pd.DataFrame(np.arange(1,21).reshape(4,5), index = list("abcd"), columns = list('ABCDE'))

In [32]:
fram1


A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20

In [36]:
fram2 = pd.DataFrame(np.arange(21,41).reshape(4,5), index = list("dabc"), columns = list('EBCDA'))

In [37]:
fram2

E   B   C   D   A
d  21  22  23  24  25
a  26  27  28  29  30
b  31  32  33  34  35
c  36  37  38  39  40

In [38]:
fram1+fram2 

A   B   C   D   E
a  31  29  31  33  31
b  41  39  41  43  41
c  51  49  51  53  51
d  41  39  41  43  41

In [44]:
fram1 = pd.DataFrame(np.arange(1,21).reshape(4,5), index = list("abtd"), columns = list('APCDE'))

In [45]:
fram2 = pd.DataFrame(np.arange(21,41).reshape(4,5), index = list("dabc"), columns = list('EBCDA'))

In [46]:
fram1

A   P   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
t  11  12  13  14  15
d  16  17  18  19  20

In [47]:
fram2

E   B   C   D   A
d  21  22  23  24  25
a  26  27  28  29  30
b  31  32  33  34  35
c  36  37  38  39  40

In [48]:
frame3 = fram1.add(fram2, fill_value=0.0)
frame3

A     B     C     D     E     P
a  31.0  27.0  31.0  33.0  31.0   2.0
b  41.0  32.0  41.0  43.0  41.0   7.0
c  40.0  37.0  38.0  39.0  36.0   NaN
d  41.0  22.0  41.0  43.0  41.0  17.0
t  11.0   NaN  13.0  14.0  15.0  12.0

In [49]:
 fram1+fram2 

A   B     C     D     E   P
a  31.0 NaN  31.0  33.0  31.0 NaN
b  41.0 NaN  41.0  43.0  41.0 NaN
c   NaN NaN   NaN   NaN   NaN NaN
d  41.0 NaN  41.0  43.0  41.0 NaN
t   NaN NaN   NaN   NaN   NaN NaN

In [54]:
 df1 = pd.DataFrame(np.arange(1,13.).reshape(3,4), columns = list('abcd'))

In [57]:
df2 = pd.DataFrame(np.arange(1,21.).reshape(4,5),columns = list('abcde'))

In [58]:
df1

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [59]:
df2

a     b     c     d     e
0   1.0   2.0   3.0   4.0   5.0
1   6.0   7.0   8.0   9.0  10.0
2  11.0  12.0  13.0  14.0  15.0
3  16.0  17.0  18.0  19.0  20.0

In [60]:
df1+df2

a     b     c     d   e
0   2.0   4.0   6.0   8.0 NaN
1  11.0  13.0  15.0  17.0 NaN
2  20.0  22.0  24.0  26.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [61]:
df3 = df1.add(df2, fill_value=0)
df3

a     b     c     d     e
0   2.0   4.0   6.0   8.0   5.0
1  11.0  13.0  15.0  17.0  10.0
2  20.0  22.0  24.0  26.0  15.0
3  16.0  17.0  18.0  19.0  20.0

In [63]:
df2.loc[1,'b'] = np.NaN

In [65]:
df1

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [66]:
df2

a     b     c     d     e
0   1.0   2.0   3.0   4.0   5.0
1   6.0   NaN   8.0   9.0  10.0
2  11.0  12.0  13.0  14.0  15.0
3  16.0  17.0  18.0  19.0  20.0

In [67]:
df1+df2

a     b     c     d   e
0   2.0   4.0   6.0   8.0 NaN
1  11.0   NaN  15.0  17.0 NaN
2  20.0  22.0  24.0  26.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [68]:
df3 = df1.add(df2, fill_value=0)
df3

a     b     c     d     e
0   2.0   4.0   6.0   8.0   5.0
1  11.0   6.0  15.0  17.0  10.0
2  20.0  22.0  24.0  26.0  15.0
3  16.0  17.0  18.0  19.0  20.0

In [69]:
fram1 = pd.DataFrame(np.arange(1,21).reshape(4,5), index = list("abtd"), columns = list('APCDE'))
fram1

A   P   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
t  11  12  13  14  15
d  16  17  18  19  20

In [70]:
fram2 = pd.DataFrame(np.arange(21,41).reshape(4,5), index = list("dabc"), columns = list('EBCDA'))
fram2

E   B   C   D   A
d  21  22  23  24  25
a  26  27  28  29  30
b  31  32  33  34  35
c  36  37  38  39  40

In [72]:
fram1+fram2

A   B     C     D     E   P
a  31.0 NaN  31.0  33.0  31.0 NaN
b  41.0 NaN  41.0  43.0  41.0 NaN
c   NaN NaN   NaN   NaN   NaN NaN
d  41.0 NaN  41.0  43.0  41.0 NaN
t   NaN NaN   NaN   NaN   NaN NaN

In [73]:
df3 = fram1.add(fram2, fill_value=0)
df3

A     B     C     D     E     P
a  31.0  27.0  31.0  33.0  31.0   2.0
b  41.0  32.0  41.0  43.0  41.0   7.0
c  40.0  37.0  38.0  39.0  36.0   NaN
d  41.0  22.0  41.0  43.0  41.0  17.0
t  11.0   NaN  13.0  14.0  15.0  12.0

In [89]:
arr = np.arange(1,21).reshape(4,5)

In [90]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [91]:
stu = list('abcd')

In [94]:
subj = list('ABCDE')

In [96]:
d1 =pd.DataFrame(arr, index=stu,columns=subj)

In [97]:
d1

A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20

In [100]:
brr = np.arange(1,21).reshape(4,5)

In [101]:
bstu = list('abce')

In [102]:
bsubj = list('ABCDF')

In [103]:
d2 =pd.DataFrame(brr, index=bstu,columns=bsubj)

In [107]:
d1

A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20

In [104]:
d2

A   B   C   D   F
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
e  16  17  18  19  20

In [105]:
d1 + d2

A     B     C     D   E   F
a   2.0   4.0   6.0   8.0 NaN NaN
b  12.0  14.0  16.0  18.0 NaN NaN
c  22.0  24.0  26.0  28.0 NaN NaN
d   NaN   NaN   NaN   NaN NaN NaN
e   NaN   NaN   NaN   NaN NaN NaN

In [106]:
d3 = d1.add(d2,fill_value=0)
d3

A     B     C     D     E     F
a   2.0   4.0   6.0   8.0   5.0   5.0
b  12.0  14.0  16.0  18.0  10.0  10.0
c  22.0  24.0  26.0  28.0  15.0  15.0
d  16.0  17.0  18.0  19.0  20.0   NaN
e  16.0  17.0  18.0  19.0   NaN  20.0

In [108]:
a1 = pd.DataFrame(np.arange(1,17).reshape(4,4), index=list('LNOB'),columns=list('APCD'))

In [111]:
a1

A   P   C   D
L   1   2   3   4
N   5   6   7   8
O   9  10  11  12
B  13  14  15  16

In [109]:
a2 = pd.DataFrame(np.arange(1,17).reshape(4,4), index=list('LNQB'),columns=list('APQD'))

In [112]:
a2

A   P   Q   D
L   1   2   3   4
N   5   6   7   8
Q   9  10  11  12
B  13  14  15  16

In [110]:
a1.add(a2,fill_value=0)

A     C     D     P     Q
B  26.0  15.0  32.0  28.0  15.0
L   2.0   3.0   8.0   4.0   3.0
N  10.0   7.0  16.0  12.0   7.0
O   9.0  11.0  12.0  10.0   NaN
Q   9.0   NaN  12.0  10.0  11.0

In [113]:
df1 = pd.DataFrame(np.arange(1,10).reshape(3,3),index = list('abc'), columns= list('ABC'))

In [116]:
df1

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [124]:
s1 = pd.Series([1,2,1], index=list('bde'))
s1

b    1
d    2
e    1
dtype: int64

In [126]:
print(df1 - s1)

    A   B   C   b   d   e
a NaN NaN NaN NaN NaN NaN
b NaN NaN NaN NaN NaN NaN
c NaN NaN NaN NaN NaN NaN


In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))

In [4]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [5]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [6]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [7]:
df2.loc[1, 'b'] = np.nan

In [8]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [9]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [10]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [11]:
df1.add(df2 , fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [12]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [13]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [14]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [15]:
df1.add(df2 , fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [16]:
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [17]:
1/ df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [18]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [19]:
df1.rdiv(0)

a    b    c    d
0  NaN  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [20]:
arr = np.arange(12.).reshape((3, 4))

In [21]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [22]:
arr[0]

array([0., 1., 2., 3.])

In [23]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [24]:
s1 = pd.Series(range(3), index=['a', 'b', 'c'])

In [25]:
my_index = s1.index

In [26]:
my_index

Index(['a', 'b', 'c'], dtype='object')

In [28]:
my_index[1:]

Index(['b', 'c'], dtype='object')

In [29]:
my_index[0]

'a'

In [30]:
my_index[1]

'b'

In [31]:
my_index[2]

'c'

In [33]:
my_index[0:3]

Index(['a', 'b', 'c'], dtype='object')

In [34]:
labels = pd.Index(np.arange(3))

In [35]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [36]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [37]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [38]:
obj2.index is labels

True

In [1]:
import numpy as np

In [2]:
import pandas as pd 

In [5]:
fram1 = pd.DataFrame(np.arange(2,12).reshape(2,5),index = list("AB"),columns = list("abcde"))

In [7]:
fram2 = pd.DataFrame(np.arange(12,22).reshape(2,5),index = list("CD"),columns = list("abcde"))

In [8]:
fram1

a  b  c   d   e
A  2  3  4   5   6
B  7  8  9  10  11

In [10]:
fram2


a   b   c   d   e
C  12  13  14  15  16
D  17  18  19  20  21

In [23]:
S_sub = pd.Series([1,2,3,4,5,6], index = list('abcdef'))

In [24]:
S_sub

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [25]:
fram1 - S_sub

a  b  c  d  e   f
A  1  1  1  1  1 NaN
B  6  6  6  6  6 NaN

In [26]:
fram2 = pd.DataFrame(np.arange(1,7).reshape(2,3),index = list("CD"),columns = list("abc"))

In [28]:
fram1 = pd.DataFrame(np.arange(7,13).reshape(2,3),index = list("EF"),columns = list("cde"))

In [29]:
fram1

c   d   e
E   7   8   9
F  10  11  12

In [30]:
fram2

a  b  c
C  1  2  3
D  4  5  6

In [31]:
fram1+fram2

a   b   c   d   e
C NaN NaN NaN NaN NaN
D NaN NaN NaN NaN NaN
E NaN NaN NaN NaN NaN
F NaN NaN NaN NaN NaN

In [32]:
fram1.add(fram2, fill_value=0)

a    b     c     d     e
C  1.0  2.0   3.0   NaN   NaN
D  4.0  5.0   6.0   NaN   NaN
E  NaN  NaN   7.0   8.0   9.0
F  NaN  NaN  10.0  11.0  12.0

In [33]:
fram2.add(fram1, fill_value=0)

a    b     c     d     e
C  1.0  2.0   3.0   NaN   NaN
D  4.0  5.0   6.0   NaN   NaN
E  NaN  NaN   7.0   8.0   9.0
F  NaN  NaN  10.0  11.0  12.0

In [53]:
p = np.arange(6)
q = np.arange(6,12)
r = np.arange(12,18)
s = np.arange(18,24)


In [54]:
dict1 = {
    'a': [1,2,3,4,5,6],
    'b': [1,2,3,4,5,6],
    'c': [ 1,2,3,4,5,6],
    'd': [ 1,2,3,4,5,6]
}

In [82]:
df = pd.DataFrame(dict1, index= list('ABCDEF'), columns = list('abcdefg'))

In [83]:
df

a  b  c  d    e    f    g
A  1  1  1  1  NaN  NaN  NaN
B  2  2  2  2  NaN  NaN  NaN
C  3  3  3  3  NaN  NaN  NaN
D  4  4  4  4  NaN  NaN  NaN
E  5  5  5  5  NaN  NaN  NaN
F  6  6  6  6  NaN  NaN  NaN

In [109]:
df = pd.DataFrame([p,q,r,s], index = list('abcd'),columns = list('PQRSTU'))

In [110]:
df

P   Q   R   S   T   U
a   0   1   2   3   4   5
b   6   7   8   9  10  11
c  12  13  14  15  16  17
d  18  19  20  21  22  23

In [101]:
npd = pd.DataFrame(np.arange(1,21).reshape(4,5),index = list ('ABCD'), columns = list('PQRST'))
npd

P   Q   R   S   T
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20

In [102]:
npd = npd.drop('P',axis=1)

In [103]:
npd

Q   R   S   T
A   2   3   4   5
B   7   8   9  10
C  12  13  14  15
D  17  18  19  20

In [107]:
npd.drop('A',axis=0, inplace = False)

Q   R   S   T
B   7   8   9  10
C  12  13  14  15
D  17  18  19  20

In [108]:
npd

Q   R   S   T
A   2   3   4   5
B   7   8   9  10
C  12  13  14  15
D  17  18  19  20

In [133]:
npd.loc[['A'],['R']]

R
A  3

In [134]:
npd

Q   R   S   T
A   2   3   4   5
B   7   8   9  10
C  12  13  14  15
D  17  18  19  20

In [137]:
npd.reindex(list('ABCDES'))

Q     R     S     T
A   2.0   3.0   4.0   5.0
B   7.0   8.0   9.0  10.0
C  12.0  13.0  14.0  15.0
D  17.0  18.0  19.0  20.0
E   NaN   NaN   NaN   NaN
S   NaN   NaN   NaN   NaN

In [138]:
npd.reindex(list('ABCDES'), method='ffill')

Q   R   S   T
A   2   3   4   5
B   7   8   9  10
C  12  13  14  15
D  17  18  19  20
E  17  18  19  20
S  17  18  19  20

In [140]:
npd.reindex(columns = list('QRSTUV'))

Q   R   S   T   U   V
A   2   3   4   5 NaN NaN
B   7   8   9  10 NaN NaN
C  12  13  14  15 NaN NaN
D  17  18  19  20 NaN NaN

In [141]:
npd.reindex(columns = list('QRSTUV'), method = 'ffill')

Q   R   S   T   U   V
A   2   3   4   5   5   5
B   7   8   9  10  10  10
C  12  13  14  15  15  15
D  17  18  19  20  20  20

In [143]:
cities = pd.DataFrame(np.arange(16).reshape(4,4), index = list('ABCD'), columns = list('PQRS'))

In [144]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [158]:
cities[0:2]

P  Q  R  S
A  0  1  2  3
B  4  5  6  7

In [160]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [161]:
cities.P

A     0
B     4
C     8
D    12
Name: P, dtype: int32

In [162]:
cities.Q

A     1
B     5
C     9
D    13
Name: Q, dtype: int32

In [164]:
cities[cities['P']>4]

P   Q   R   S
C   8   9  10  11
D  12  13  14  15

In [166]:
cities.P[2:]

C     8
D    12
Name: P, dtype: int32

In [170]:
cities.P[cities.P>4]

C     8
D    12
Name: P, dtype: int32

In [171]:
cities[cities.P<4]

P  Q  R  S
A  0  1  2  3

In [172]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [174]:
cities.loc['B',['Q','R']]

Q    5
R    6
Name: B, dtype: int32

In [176]:
cities.loc[['B','C'],['Q','R']]

Q   R
B  5   6
C  9  10

In [177]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [178]:
cities.loc[['A','B']]

P  Q  R  S
A  0  1  2  3
B  4  5  6  7

In [179]:
cities.loc[['A','B'],['P']]

P
A  0
B  4

In [180]:
cities.loc[['A','B'],['P','Q']]

P  Q
A  0  1
B  4  5

In [181]:
cities.loc['A','Q']

1

In [182]:
cities.loc['B','Q']

5

In [183]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [185]:
cities.loc[['A','B','D'],['P','Q','R']]

P   Q   R
A   0   1   2
B   4   5   6
D  12  13  14

In [186]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [187]:
cities.iloc[[0,1,3],[0,1,2]]

P   Q   R
A   0   1   2
B   4   5   6
D  12  13  14

In [190]:
cities.iloc[1,[1,2]]

Q    5
R    6
Name: B, dtype: int32

In [192]:
cities.P[cities.P>=4]

B     4
C     8
D    12
Name: P, dtype: int32

In [193]:
cities

P   Q   R   S
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [199]:
cities.iloc[1:3,1:3]

Q   R
B  5   6
C  9  10

In [200]:
cities.loc['B':'D','Q':'S']

Q   R   S
B   5   6   7
C   9  10  11
D  13  14  15

In [204]:
cities.iloc[ ::2, ::2]

P   R
A  0   2
C  8  10